add read for almost all and struct for almost all
sreznick/heapmaster pull request #8
Opened 2024-12-16 19:13 UTC by SunnySt4r

2024-12-17 22:58 UTC, romanpovol requested changes

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +type LoadClass struct {
what are we going to do with this object?
https://github.com/sreznick/heapmaster/blob/main/internal/hprof/record.go#L13

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +	defer output.Close()
As if "defer output.Close()" should be written after if, even the static analyzer suggest

> should check error returned from os.OpenFile() before deferring output.Close() (SA5001)go-staticcheck


for what is there an output at all at the moment?

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +	Magic string
please run go fmt on this file

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +		return header, err
please, use `fmt.Errorf` for every err

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +func readRootMonitorUsed(data []byte) (RootMonitorUsed, error) {
maybe
```
func readRootMonitorUsed(data []byte) RootMonitorUsed {
  return RootMonitorUsed{
    ObjectId: int64(binary.BigEndian.Uint64(data[:8])),
  }
}
```

this is how almost every function can be implemented

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +	for i := 0; i < 20;  {
why 20?

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +func readLoadClass(data []byte) (LoadClass, error) {
for what return error? (in almost all functions)

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +	nothing_1 int64
for what store these fields (nothing_1 and nothing_2)?

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +		fmt.Println("Usage: go run parser.go <file.hprof>")
> parser.go


?


func main must be in the main package;
It seems to me that this whole function needs to be moved to another file

2024-12-17 22:58 UTC, romanpovol commented on internal/hprof/class.go
> +		fmt.Printf("Error reading header: %v\n", err)
`Errorf`

2024-12-18 07:29 UTC, SunnySt4r commented on internal/hprof/class.go
> +	nothing_1 int64
It's "reserved" fields, like in doc https://hg.openjdk.org/jdk6/jdk6/jdk/raw-file/tip/src/share/demo/jvmti/hprof/manual.html#mozTocId848088

2025-01-20 23:51 UTC, sreznick requested changes

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +func readRootMonitorUsed(data []byte) (RootMonitorUsed, error) {
Yes, it makes sense to return `something, nil` only if it is particular case of general interface returning error.

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +	// Read the class object ID (8 bytes)
```
 bytes.NewReader(data)
```

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +		fmt.Printf("Error opening file: %v\n", err)
`Errorf`

here and in similar cases

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +		if record.Tag == 0x01 {
Avoid using magic constants.

Go pattern for "enum" is here:

https://github.com/sreznick/heapmaster/blob/945ff00fb962e8502284a1444b8cf65fe4cc33e4/internal/hprof/record.go#L10C1-L14C2

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +		0xFF: func(data []byte) (interface{}, error) { return readRootUnknown(data) },
```
0xFF: readRootUnknown,
....
```

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +	ElementType byte
Use type alias and consts

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +	subTagMap[0x01](nil) // just to avoid unused error
1. Why do we need such unused variable in main branch  ?
2. If you need keep unused variable and make compiler happy, idiomatic way is following:
```
_ = sugTagMap
```

2025-01-20 23:51 UTC, sreznick commented on internal/hprof/class.go
> +		fmt.Println("Usage: go run parser.go <file.hprof>")
In basic version of project I intentionally used command line utility - to show how cli should be allocated and how to use cobra library to parse command line arguments.

So if you want to introduce some CLI utility use my CLI utility as example.

If you want to make some test then use go unit test facility.

If you have hard time trying to understand how to use go unit tests - feel free to ask me.

2025-01-21 15:54 UTC, sreznick commented on internal/hprof/class.go
> +		return header, err
Not every in general.

Sometimes it makes just to propagate  error as is.

Wrap err into fmt.Errorf is useful when we want to reformulate error in higher-level terms

2025-02-07 00:18 UTC, sreznick approved these changes

2025-02-07 00:19 UTC, sreznick approved these changes

2025-02-07 08:06 UTC, SunnySt4r commented on internal/hprof/class.go
> +type LoadClass struct {
I rename object in record.go

2025-02-07 08:17 UTC, sreznick approved these changes

2025-02-07 08:19 UTC, merged